name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Kobiton Appium tests
        uses: kobiton/execute-appium-test-github-action@v1.0.0
        with:
          kobi_username: ${{ secrets.KOBITON_USERNAME }}
          kobi_api_key: ${{ secrets.KOBITON_API_KEY }}
          executor_url: https://executor.kobiton.com
          executor_username: ${{ secrets.KOBITON_EXECUTOR_USERNAME }}
          executor_password: ${{ secrets.KOBITON_EXECUTOR_PASSWORD }}
          git_repo_url: https://github.com/emmanuelmtzrdeloitte/kubitondemo.git
          git_repo_branch: main
          app_id: kobiton-store:v725763
          use_custom_device: 'true'
          device_name: 'Pixel 8'
          device_platform_version: '15'
          device_platform: 'Android'
          root_directory: '/'
          command: './gradlew test'
          wait_for_execution: 'true'
